server:
  port: 8080
spring:  
  cloud:
    gateway:
      routes:
        - id: movie
          uri: lb://MOVIE-SERVICE/
          predicates:
           - Path=/movies/**
        - id: catalog
          uri: lb://CATALOG-SERVICE
          predicates:
           - Path=catalog/**